### ISSUE TITLE
[Bug] AutofacServiceProvider allows scoped services to be injected into worker services

### ISSUE THREAD

**Issue by alsami** [autofac/Autofac.Extensions.DependencyInjection#106]
**Describe the bug**
When implementing a worker-service based on `BackgroundService` (`Microsoft.Extensions.Hosting.Abstractions`) and injecting a scoped service into that worker-service, Microsoft's implementation of `IServiceProvider` throws an error but Autofac's does not.

**To reproduce**
I've created a [sample project](https://github.com/alsami/Autofac.ScopedServiceInWorkerService), where only one line needs to be uncommented to see that when `AutofacServiceProviderFactory` has been used and its dependencies registered, this does not happen anymore.

1. Start the service to see the exception
2. Then stop the service and uncomment line six
3. Run the service again to see that the exception does not occur anymore

**Full exception with stack trace:**

```text
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: Autofac.ScopedServiceInWorkerService.Worker': Cannot consume scoped service 'Autofac.ScopedServiceInWorkerService.ScopedService' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: Autofac.ScopedServiceInWorkerService.Worker': Cannot consume scoped service 'Autofac.ScopedServiceInWorkerService.ScopedService' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.
 ---> System.InvalidOperationException: Cannot consume scoped service 'Autofac.ScopedServiceInWorkerService.ScopedService' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScopeCache(ServiceCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitRootCache(ServiceCallSite singletonCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateCallSite(ServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.OnCreate(ServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Program.<Main>$(String[] args) in /home/sami/Dev/alsami/Autofac.ScopedServiceInWorkerService/src/Autofac.ScopedServiceInWorkerService/Program.cs:line 4
   at Program.<Main>(String[] args)
```

**Assembly/dependency versions:**
```xml
<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="8.0.0" />
<PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
```

**Additional context**
I am not sure whether that is to be expected or not. My understanding is that when injecting a scoped service into a singleton, the scoped service behaves like a singleton while it shouldn't. In some cases people might not use the [described approach from MS](https://docs.microsoft.com/en-us/dotnet/core/extensions/scoped-service#rewrite-the-worker-class) and run into unexpected behavior that is hard to understand. 

If this should be part of the main repository instead, let me know, I can move it over.

**Comment by tillig** [comment]
Unclear if this is a bug. The way the error reads, it's Microsoft trying to stop you from creating [captive dependencies](https://autofac.readthedocs.io/en/latest/lifetime/captive-dependencies.html). Is that something we should guard against? Sometimes you do want to inject a scoped/transient dependency into a singleton, like to give a singleton its own instance of a cache that it can keep alive.

**Comment by alsami** [comment]
Oh, didn't know this was by design. I am just thinking about stuff like EF where people would by default have a scoped registration that can cause problems. Since it's described in the docs I'd agree that this isn't a bug but a feature. Happy to close the issue then.

**Comment by tillig** [comment]
Let's close it for now, and if other folks see it and have issues we can reopen it. I get the feeling there are going to be a few of these sorts of interesting things that will be different between MS DI and, like, every other container out there. Unclear if they should put this in a spec test or not, but I think requiring every conforming container to guard against captive dependencies is maybe a bridge too far.
