### ISSUE TITLE
Can't create ASP.Net Core webhost using a child scope

### ISSUE THREAD

**Issue by stephendrew** [autofac/Autofac.Extensions.DependencyInjection#27]
Hi,

I am trying to create an ASP.Net Core (mvc 2.0.2, kestrel 2.0.1) webhost using Autofac in place of the Microsoft dependency injection stuff.

I am running several "engines", one or more of which might be an ASP.Net Core webhost.  I have a container defined at the application level which is used to resolve these engines.

However, I don't want to pollute the root scope with stuff related to ASP.Net Core, so I want to use a nested scope for the DI in each webhost.

You can see a repro of my situation here:

https://gist.github.com/stephendrew/9d3b5674b152c6cb00cc004e9d8bcbf1

Engine1 does nothing, but highlights what I want to do.  Engine2 tries to create a webhost using a nested lifetime scope.

It fails with:

```
The requested service 'Microsoft.AspNetCore.Hosting.Server.IServer' has not been registered
```

```
Engine 1 started
Engine 2 started
Application startup exception: Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Microsoft.AspNetCore.Hosting.Server.IServer' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

Perhaps I am doing something that is wrong?  I tried to follow the guide here: http://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#quick-start-without-configurecontainer

Note that my repro still fails if I replace the nested scope with the code from the guide:

```csharp
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            var cb = new ContainerBuilder();
            cb.Populate(services);
            var container = cb.Build();

            // Return an Autofac provider
            return new AutofacServiceProvider(container);
        }
```

Although the error is slightly different:

```
The requested service 'System.IServiceProvider' has not been registered.
```

Thanks

**Comment by stephendrew** [comment]
OK, so I was confusing things by putting `ILifetimeScope` in the original service collection.

If I remove it, then it's fine in both cases...

```csharp
var descriptor = services.SingleOrDefault(sd => sd.ServiceType == typeof(ILifetimeScope));
if (descriptor != null)
    services.Remove(descriptor);
```
