### ISSUE TITLE
Method not found while configure services under Linux

### ISSUE THREAD

**Issue by nimbusparis** [autofac/Autofac.Extensions.DependencyInjection#34]
I've trouble using Autofac under Linux using dotnet core 2.1

Linux version 4.15.0-36-generic (buildd@lgw01-amd64-031) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018
dotnet 2.1.403

i get the following exception:
Unhandled Exception: System.MissingMethodException: Method not found: 'Void Autofac.Extensions.DependencyInjection.AutofacServiceProvider..ctor(Autofac.IComponentContext)'.
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at ImageHuntBot.Program.Main(String[] args)

This code work perfectly under Windows 10, same version of dotnet core (2.1.403)

Please advise

**Comment by tillig** [comment]
This isn't enough info to provide assistance. Need minimal repro. Also, make sure literally everything in each setup is the same - same .NET Core SDK, same .NET Core base app and ASP.NET Core stuff installed, everything. You could also try doing dotnet publish and target Linux from the windows box as a test.

**Comment by IGx89** [comment]
I just ran into this error myself, after updating my Autofac dependency (and others). I tried rebuilding, etc. to no avail. Finally the error went away after I manually deleted my bin and obj folders. Posting this in case anyone else runs into this error too.
